# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-13 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181213_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 12, 13, 21, 24, 18, 304195, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
